- src/client.rs
- src/search.rs
- tests/search.rs
The find/search interface is now usable and correctly returns the songs
being searched for according to the Query criteria. The most important
changes are:
* Don't let Query own the Client connection, but lend the Query to the
Client instead for the duration of the query run.
* Fix how Query struct generates its string representation (spacing,
quoting).
(An issue that Query interface isn't fully chainable still
persists. This is possible to work around using `let` bindings for now.)
This should fix issue #4 (i'm now able to use the `find` command end-to-end in my app).
> Fix the find/search functionality

- src/status.rs
The elapsed time duration is created with millisecond precision by
multiplying the second float value by 1000. Such value then has to be
fed into Duration::milliseconds rather than Duration::seconds to produce
a correctly scaled Duration instance.
> Fix the elapsed time counter

- src/status.rs
This allows `src/status.rs` to be formatted with `rustfmt` (see https://github.com/rust-lang-nursery/rustfmt/issues/1265).
> Use `?` in status.

- examples/example.rs
- src/client.rs
- src/search.rs
- tests/search.rs
Fixes #11.
I'm not sure if the window stuff works; I don't have mpd 0.20 here. 
I wonder if there is some clever way to handle the version differences and only expose supported options?
> Don't include window and group in Query.

- src/client.rs
- src/convert.rs
- src/idle.rs
- src/proto.rs
- src/search.rs
- src/status.rs
- tests/search.rs
Rather than littering the code with calls so `format!`, pass all the command arguments as structured data, so there is one place where everything can be quoted.
Fixes #16.
> Be principled about formatting commands.

- src/lib.rs
Since we turn warnings into errors on travis, this should still catch mistakes, but make it easier to add test functionality before writing docs.
> Only warn on missing docs.

- src/client.rs
- src/error.rs
- src/idle.rs
- src/plugin.rs
- src/proto.rs
I was playing around with porting to tokio, and having a bunch of parsing logic in `client` makes the porting harder.
> Add some more helpers for parsing responses.

- .travis.yml
Also pin clippy version that is compatible with pinned nightly.
> Pin to a version of nightly that has a working rust-clippy.

- src/client.rs
- src/error.rs
- src/idle.rs
- src/message.rs
- src/mount.rs
- src/output.rs
- src/playlist.rs
- src/plugin.rs
- src/proto.rs
- src/search.rs
- src/song.rs
- src/status.rs
- src/sticker.rs
- tests/helpers/daemon.rs
I just copied and pasted the `elapsed` handling, and tested that it works locally.  Test suite passes, tested against MPD 0.19  and MPD 0.20.
> Parse duration as a float instead of integer. Fixes #27

- Cargo.toml
- src/client.rs
- src/convert.rs
- src/error.rs
- src/idle.rs
- src/lib.rs
- src/macros.rs
- src/message.rs
- src/mount.rs
- src/output.rs
- src/playlist.rs
- src/plugin.rs
- src/proto.rs
- src/reply.rs
- src/search.rs
- src/song.rs
- src/stats.rs
- src/status.rs
- src/sticker.rs
- src/version.rs
- tests/options.rs
Fix some warnings emitted by a 1.39 compiler. No functional changes.
> Adapt for more recent Rust releases

- src/client.rs
- src/proto.rs
Fixes `find_sticker_eq` always returning a bad request response due to the missing operator argument.
Worth noting the protocol also supports `>` or `<`, which are currently not mapped by the library
> fix(client): find_sticker_eq missing `=` argument

- src/client.rs
- src/convert.rs
- src/proto.rs
- src/song.rs
Tags in MPD are not a key-value mapping, but an array of key-value
pairs. Some tags commonly have multiple values, such as PERFORMER, and
by storing this data in a map we only get one of the performers.
> Allow tags with multiple values

- src/search.rs
The provided test case fails to build on master, but seems like a valid
use case. See: https://stackoverflow.com/questions/58878192/cannot-borrow-xxx-as-mutable-more-than-once-at-a-time-when-using-mpds-query/58879004#58879004 and #40 for a discussion.
> Fix liftimes in query API

- src/client.rs
The version returned on connection by MPD is the version of the protocol, not of the daemon.
See also: https://mpd.readthedocs.io/en/latest/protocol.html#protocol-overview
> Fix Client.version doc comment

- src/output.rs
- tests/outputs.rs
The `plugin` field returned by the [`outputs` command](https://mpd.readthedocs.io/en/stable/protocol.html#command-outputs) is currently missing.
> Add plugin name to output struct

- tests/helpers/daemon.rs
Currently, the [`volume` test](https://github.com/kstep/rust-mpd/blob/c31a9ba36c9c5107da392e1cab17da9c0c5dee16/tests/options.rs#L51) fails with:
> thread 'volume' panicked at 'called `Result::unwrap()` on an `Err` value: Server(ServerError { code: UnknownCmd, pos: 0, command: "setvol", detail: "No mixer" })'
when trying to set volume, as the `null` audio output has no mixer.
The [`null` mixer](https://mpd.readthedocs.io/en/stable/user.html#configuring-audio-outputs) allows to set volume without actual effect.
> Set null mixer type for test audio output

- src/error.rs
- src/idle.rs
- src/status.rs
The `use Enum::*` for enums in `match` blocks to avoid repeating the enum name can be a footgun in case a variant is later removed - inside the `match` block the removed variant becomes a catchall variant.
And if one variant is removed and another is added, the removed variant will catch the newly added one, without us needing to handle the newly added variant.
For a better explanation: https://youtu.be/8j_FbjiowvE?t=97
> Avoid `use Enum::*`

- Cargo.toml
- benches/options.rs
I believe this is leftover as `std::os::unix::net::UnixStream` is [already being used](https://github.com/kstep/rust-mpd/blob/5765e02bbc3b6c1dc2571ac6e44f53402972fe68/tests/helpers/daemon.rs#L7) in tests.
> Drop `unix_socket` dependency

- Cargo.toml
- tests/helpers/daemon.rs
`tempdir` was merged into [`tempfile`](https://crates.io/crates/tempfile) and [is now deprecated](https://github.com/rust-lang-deprecated/tempdir#deprecation-note).
> Use `tempfile` crate instead of `tempdir`

- src/client.rs
For a personal project of mine, I needed to have quick access to mpd "listallinfo" command. 
Since the mpd "listall" command was already implemented, and a Vec<Song> structure could already be built from the mpd response, I added the mpd "listallinfo" command. After testing the new command in my project, I had the behaviour I expected.
Let me know if I need to add more code for the pr to be valid.
> added listallinfo command

- src/error.rs
- src/song.rs
- src/status.rs
- tests/options.rs
- Use `Duration::try_from_secs_f64` when parsing duration with decimal point.
- Add new variant `BadDuration` to `ParserError` for handling the errors when the float value is not a valid duration (negative, would overflow the underlying `u64` or is not a number).
- Do not discard duration parsing errors with `.ok()`.
> Handle errors when creating duration from float
